const { cmd, commands } = require('../command');
const { runtime } = require('../lib/functions');
const config = require('../config');

cmd({
  pattern: "listmenu",
  alias: ["menu2", "help", "list"],
  desc: "Show all bot commands and info",
  category: "menu",
  react: "📋",
  filename: __filename
}, async (client, m) => {
  try {
    const totalCommands = Object.keys(commands).length;
    let aliasCount = 0;
    const categories = [...new Set(Object.values(commands).map(c => c.category))];
    const categorized = {};

    Object.values(commands).forEach(c => {
      if (c.alias) aliasCount += c.alias.length;
      if (!categorized[c.category]) categorized[c.category] = [];
      categorized[c.category].push(c);
    });

    let text = `╭─〔 *📋 PK-XMD BOT MENU* 〕─⬣\n`
      + `│\n`
      + `├ 🤖 *Bot Name:* PK-XMD\n`
      + `├ 👑 *Owner:* ${config.OWNER_NAME || 'Private'}\n`
      + `├ ⏱ *Uptime:* ${runtime(process.uptime())}\n`
      + `├ 💻 *Platform:* Heroku\n`
      + `├ 📦 *Version:* 4.0.0\n`
      + `│\n`
      + `├ 📊 *Total Commands:* ${totalCommands}\n`
      + `├ 🧩 *Total Aliases:* ${aliasCount}\n`
      + `├ 🗂️ *Categories:* ${categories.length}\n`
      + `╰────────────────────⬣\n\n`;

    for (const [category, cmds] of Object.entries(categorized)) {
      text += `╭─〔 *${category.toUpperCase()}* 〕─⬣\n`;
      cmds.forEach(c => {
        text += `├ 📌 *.${c.pattern}*\n`;
        if (c.desc) text += `│ 📄 ${c.desc}\n`;
        if (c.alias && c.alias.length > 0) text += `│ 🔁 ${c.alias.map(a => `.${a}`).join(', ')}\n`;
        if (c.use) text += `│ 💡 Usage: ${c.use}\n`;
      });
      text += `╰────────────────────⬣\n\n`;
    }

    text += `> 🔖 *Powered by Pkdriller*\n`;

    // Send menu
    await client.sendMessage(m.chat, {
      text,
      quoted: {
        key: {
          fromMe: false,
          participant: "0@s.whatsapp.net",
          remoteJid: "120363288304618280@newsletter",
        },
        message: {
          contactMessage: {
            displayName: "PK-XMD",
            vcard: `BEGIN:VCARD\nVERSION:3.0\nN:PK-XMD;;;\nFN:PK-XMD\nitem1.TEL;waid=254700000000:+254700000000\nitem1.X-ABLabel:Mobile\nEND:VCARD`,
          },
        },
      },
      contextInfo: {
        externalAdReply: {
          title: "PK-XMD WhatsApp Bot",
          body: "Menu generated by PK-XMD",
          mediaType: 1,
          previewType: "NONE",
          renderLargerThumbnail: false,
          sourceUrl: "https://github.com/pkdriller/PK-XMD"
        },
        forwardingScore: 999,
        isForwarded: true,
        forwardedNewsletterMessageInfo: {
          newsletterJid: "120363288304618280@newsletter",
          newsletterName: "PK-XMD Official"
        }
      }
    });

  } catch (err) {
    console.error('Error in listmenu:', err);
    await client.sendMessage(m.chat, {
      text: `❌ Failed to generate menu:\n${err.message || err}`
    });
  }
});
            
